// @ts-check

import { compactRendererVisualProfile,createAeroPlayCanvasRenderer,gameplayIconIds,rasterizeBrandingIconAtlas } from "../../src/index.js";
const surfaces=[...document.querySelectorAll(".surface")],canvases=[...document.querySelectorAll("canvas")],status=document.querySelector("#status");
const renderers=canvases.map((canvas)=>{if(!(canvas instanceof HTMLCanvasElement))throw new Error("Testbed canvas is missing");const renderer=createAeroPlayCanvasRenderer();renderer.attach(canvas);return renderer;});
const fallbackManifest={schemaId:"aerobeat.branding.web-gameplay-icons.v1",schemaVersion:1,colorContract:"currentColor",webglContract:"alpha-mask-atlas-input",assets:gameplayIconIds.map((id)=>({id,file:`${id.replaceAll(".","-")}.svg`,viewBox:id==="feedback.great"?"0 0 128 32":id.includes("guard")?"0 0 48 24":"0 0 64 64"}))};
const fallbackSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path fill="currentColor" d="M8 28h22V12l26 20-26 20V36H8z"/></svg>`;let manifest=fallbackManifest,brandingBase="";try{const response=await fetch("/branding/manifest.json");if(response.ok){manifest=await response.json();brandingBase="/branding/";}}catch{}
const atlas=await rasterizeBrandingIconAtlas(manifest,{resolveUrl:(asset)=>brandingBase?`${brandingBase}${asset.file}`:`data:image/svg+xml,${encodeURIComponent(fallbackSvg)}`});for(const renderer of renderers)renderer.uploadIconAtlas(atlas);
const gridTargets=[
  {id:"straight",kind:"punch",hand:"left",family:"straight",cell:5,cells:[],lane:"left",beatCenterMs:1000},
  {id:"hook",kind:"punch",hand:"right",family:"hook",cell:6,cells:[],lane:"right",beatCenterMs:1100},
  {id:"guard",kind:"guard",hand:"both",family:"crossed_guard",cell:null,cells:[1,2],lane:null,beatCenterMs:1200},
  {id:"squat",kind:"obstacle",hand:"neutral",family:"squat",cell:null,cells:[9],lane:null,beatCenterMs:1300}
];
function draw(){renderers.forEach((renderer,index)=>renderer.resize({widthCssPx:surfaces[index].clientWidth,heightCssPx:surfaces[index].clientHeight,devicePixelRatio:window.devicePixelRatio}));const primary=renderers[0].renderGameplayFrame({presentation:"flow",nowMs:1000,timingWindowBeforeMs:180,timingWindowAfterMs:180,targets:[{id:"near",kind:"flow",hand:"left",family:"flow",cell:5,cells:[],lane:null,beatCenterMs:1350,direction:"right"},{id:"far",kind:"flow",hand:"right",family:"flow",cell:5,cells:[],lane:null,beatCenterMs:2500,direction:null},{id:"wall",kind:"obstacle",hand:"neutral",family:"obstacle",cell:null,cells:[0,4],geometry:{schema:"aerobeat/flow_obstacle_geometry",version:1,coordinateSpace:"beatsaber_lane_layer",x:0,y:1,width:1,height:2},lane:null,beatCenterMs:1500,intervalStartMs:1500,intervalEndMs:2100}],blockedCells:[3],safeCells:[8],overlay:"none"});const secondary=renderers[1].renderGameplayFrame({presentation:"boxing_lanes",nowMs:1000,timingWindowBeforeMs:180,timingWindowAfterMs:240,targets:gridTargets.slice(0,2),overlay:"none"});const snapshot={ready:true,primary:primary.status,secondary:secondary.status,primaryObjects:primary.model.objects.length,secondaryObjects:secondary.model.objects.length,primaryModel:primary.model,secondaryModel:secondary.model};if(status)status.textContent=JSON.stringify({primary:primary.status,secondary:secondary.status},null,2);globalThis.__AERO_RENDERER_TEST__={...snapshot,resize:draw,renderers,compactRendererVisualProfile,atlasWidth:atlas.width,atlasHeight:atlas.height,atlasCellSize:atlas.width/4,gridTargets};}
function displayedAlphaPixels(canvas){const sample=new OffscreenCanvas(canvas.width,canvas.height);const context=sample.getContext("2d",{willReadFrequently:true});context.drawImage(canvas,0,0);const pixels=context.getImageData(0,0,sample.width,sample.height).data;let count=0;for(let index=3;index<pixels.length;index+=4)if(pixels[index]>0)count+=1;return count;}
draw();
globalThis.__AERO_RENDERER_TEST__.initialDisplayedAlpha=canvases.map(displayedAlphaPixels);
