// @ts-check

export { AeroPlayCanvasRenderer, aeroPlayCanvasRendererServiceId, createAeroPlayCanvasRenderer } from "./renderer-facade.js";
export { createTestPresentationConfig, defaultTestPresentationConfig, maximumTestPresentationConfigBytes, normalizeTestPresentationConfig, parseTestPresentationConfig, serializeTestPresentationConfig, testPresentationBounceOffsetY, testPresentationConfigArtifactFilename, testPresentationConfigArtifactMimeType, testPresentationConfigBounds, testPresentationConfigSchema, testPresentationConfigVersion, testPresentationEasings, testPresentationSkyModes, testPresentationSkyOffsetY } from "./test-presentation-config.js";
export { createGameplayVisualExperimentConfig, defaultGameplayVisualExperimentConfig, gameplayGuidanceBandModes, gameplayVisualExperimentConfigBounds, gameplayVisualExperimentConfigSchema, gameplayVisualExperimentConfigVersion, normalizeGameplayVisualExperimentConfig, parseGameplayVisualExperimentConfig, serializeGameplayVisualExperimentConfig } from "./gameplay-visual-experiment-config.js";
export { PlayCanvasGameplayAssetPreloader } from "./gameplay-asset-loader.js";
export { gameplayAssetAuditCommit, gameplayAssetAuditTree, gameplayAssetForRole, gameplayAssetIds, gameplayAssetInventorySha256, gameplayAssetProofSha256, gameplayAssetRawTree, gameplayAssetReleaseVersion, gameplayAssetSet, gameplayAssetSourceCommit, gameplayAssetSourceTree, gameplayAssets, resolveGameplayAssetUrl } from "./gameplay-assets.js";
export { aftermathLaunchVelocity, aftermathObjects, aftermathPose, aftermathSliceOffsetX, buildGameplaySceneModel, COLLIDER_OVERLAY_CAM_OFFSET_WU, defaultGameplayTimingWindow, defaultRendererThemeTokens, defaultRendererTuning, gameplayIconIds, gameplayWorldGrid, hazardContactEnvelopeIntensity, hazardContactIntensity, hazardVignetteParamsForFrame, hazardWallContactActiveIntensity, hazardWallContactIntensity, hazardWallContactReleasedIntensity, rendererVisualScaleBounds, timestampToWorldZ, toleranceConeGeometry, worldPositionForCell } from "./gameplay-scene-model.js";
export { normalizeBrandingIconManifest, normalizeIconAtlasData, rasterizeBrandingIconAtlas } from "./icon-atlas.js";
export { colorTokenToRgba, compactRendererVisualProfile, defaultRendererVisualProfile, normalizeBackgroundProjection, normalizeRendererTheme, normalizeRendererTuning, normalizeRendererVisualProfile, rendererTuningFromVisualProfile, rendererVisualScalesIdentity } from "./visual-profiles.js";
export { computeMediaContentRect, mapNormalizedLandmarkToClipSpace, mapNormalizedLandmarkToViewport, normalizeOverlaySurfaceDescriptor } from "./landmark-mapping.js";
