// @ts-check

import * as pc from "playcanvas";
import { isThemeDescriptor } from "@aerobeat/web-contracts/theme-contracts";
import { defaultTestPresentationConfig, normalizeTestPresentationConfig } from "./test-presentation-config.js";
import { defaultGameplayCameraPose, gameplayCameraPoseArtifactFilename, gameplayCameraPoseArtifactMimeType, normalizeGameplayCameraPose, serializeGameplayCameraPose } from "./gameplay-camera-pose.js";
import { defaultGameplayVisualExperimentConfig, normalizeGameplayVisualExperimentConfig } from "./gameplay-visual-experiment-config.js";
import { PlayCanvasEnvironmentAssetOwner } from "./environment-asset-owner.js";
import { PlayCanvasGameplayAssetPreloader } from "./gameplay-asset-loader.js";
import { gameplayAssetMaterialRole } from "./gameplay-assets.js";
import { normalizeIconAtlasData } from "./icon-atlas.js";
import { mapNormalizedLandmarkToViewport, normalizeOverlaySurfaceDescriptor } from "./landmark-mapping.js";
import { buildGameplaySceneModel, defaultRendererThemeTokens, gameplayWorldGrid } from "./gameplay-scene-model.js";
import { colorTokenToRgba, defaultRendererVisualProfile, normalizeBackgroundProjection, normalizeRendererTheme, normalizeRendererVisualProfile, rendererTuningFromVisualProfile } from "./visual-profiles.js";

export const aeroPlayCanvasRendererServiceId="aero.renderer.playcanvas";
const cursorRoles=Object.freeze(["nose","left_wrist","right_wrist"]);
const internalEffectivePaletteSymbol=Symbol.for("aerobeat.web-renderer.internal-effective-palette");
/** @type {WeakMap<AeroPlayCanvasRenderer,Readonly<{left:string,right:string}>|null>} */
const effectiveMarkerPalettes=new WeakMap();
/** @type {WeakMap<AeroPlayCanvasRenderer,{offset:{x:number,y:number},lastTimeMs:number|null}>} */
const productionCameraStates=new WeakMap();
const debugMovementIntents=Object.freeze(["forward","back","left","right","down","up"]);
const debugSpeedModes=Object.freeze(["normal","boost"]);
const debugMouseCaptureModes=Object.freeze(["pointer","fallback"]);
const debugKeyIntents=Object.freeze({KeyW:"forward",KeyS:"back",KeyA:"left",KeyD:"right",KeyQ:"down",KeyE:"up"});
const DEBUG_NORMAL_UNITS_PER_SECOND=3.5;
const DEBUG_BOOST_UNITS_PER_SECOND=12;
const DEBUG_MAX_DELTA_MS=100;
const DEBUG_TOUCH_TAP_MAX_MS=320;
const DEBUG_TOUCH_TAP_MAX_MOVE_PX=12;
const DEBUG_POSITION_BOUNDS=Object.freeze({x:40,yMin:-8,yMax:32,zMin:-72,zMax:32});
const PRODUCTION_CAMERA_MAX_DELTA_MS=100;
const MAX_GUIDANCE_GLYPH_TEXTURES=16;
const GRID_COLUMN_PITCH=gameplayWorldGrid.columnX[1]-gameplayWorldGrid.columnX[0],GRID_ROW_PITCH=gameplayWorldGrid.rowY[0]-gameplayWorldGrid.rowY[1];
const GRID_LEFT=gameplayWorldGrid.columnX[0]-GRID_COLUMN_PITCH/2,GRID_TOP=gameplayWorldGrid.rowY[0]+GRID_ROW_PITCH/2;

/** One assembly-owned renderer and PlayCanvas Application per connected game. */
export class AeroPlayCanvasRenderer {
  constructor(options={}){
    this.serviceId=aeroPlayCanvasRendererServiceId;
    this.contextAttributes=options.contextAttributes??{alpha:true,antialias:true,premultipliedAlpha:true,preserveDrawingBuffer:false};
    this.canvas=null;this.app=null;this.appStarted=false;this.cameraEntity=null;this.fixedCamera=null;this.gameplayGridLayer=null;this.gameplayGuidanceUnderLayer=null;this.gameplayTargetLayer=null;this.gameplayGuidanceOverLayer=null;this.pool=[];this.assetPools=new Map();this.assetPoolGeneration=-1;this.assetMaterials=new WeakMap();this.materialStates=new WeakMap();this.markerPool=[];this.markerPoolMode="none";this.feedbackPool=[];this.feedbackTextures=new Map();this.guidanceGlyphPool=[];this.guidanceGlyphTextures=new Map();this.guidanceHaloPool=[];this.activeCount=0;this.overlayEntities=[];this.entityMaterials=new WeakMap();this.ownedMaterials=new Set();
    this.iconAtlasData=null;this.iconEntries=new Map();this.iconTexture=null;this.iconAtlasError=null;this.atlasRestorePending=false;
    this.state="unsupported";this.contextLost=false;this.destroyed=false;this.errorMessage=null;this.frameCount=0;this.drawCount=0;this.contextRestoreCount=0;
    this.widthCssPx=0;this.heightCssPx=0;this.devicePixelRatio=1;this.theme=defaultRendererThemeTokens;this.visualProfile=defaultRendererVisualProfile;this.tuning=rendererTuningFromVisualProfile(this.visualProfile);this.testPresentationConfig=defaultTestPresentationConfig;this.gameplayVisualExperimentConfig=defaultGameplayVisualExperimentConfig;this.productionCameraNow=typeof options.now==="function"?options.now:()=>globalThis.performance?.now?.()??Date.now();productionCameraStates.set(this,{offset:{x:0,y:0},lastTimeMs:null});
    effectiveMarkerPalettes.set(this,null);Object.defineProperty(this,internalEffectivePaletteSymbol,{configurable:false,enumerable:false,writable:false,value:Object.freeze((left,right)=>{if(this.destroyed)return this.describe();if(left===null&&right===null){effectiveMarkerPalettes.set(this,null);return this.describe();}if(!isOpaqueUppercaseColor(left)||!isOpaqueUppercaseColor(right))throw new TypeError("Effective marker palette is invalid");effectiveMarkerPalettes.set(this,Object.freeze({left,right}));return this.describe();})});
    this.themeId="aero.theme.default";this.themeVersion="1";this.themeHash="theme-default";this.background=normalizeBackgroundProjection(null);this.lastModel=null;this.sceneDiagnostics=emptySceneDiagnostics();
    /** @type {{instanceCount:number,assetId:string,roles:readonly string[],depthTest:boolean,depthWrite:boolean,sourceMode?:string}} */
    this.cursorDiagnostics=Object.freeze({instanceCount:0,assetId:"athlete-marker/sphere-v1",roles:Object.freeze([]),depthTest:true,depthWrite:true});
    this.debugEnabled=false;this.debugYaw=defaultGameplayCameraPose.rotationEulerDegrees.yYaw*Math.PI/180;this.debugPitch=defaultGameplayCameraPose.rotationEulerDegrees.xPitch*Math.PI/180;this.debugPosition={...defaultGameplayCameraPose.position};this.debugProjection={...defaultGameplayCameraPose.projection};this.debugListeners=[];
    this.debugNow=typeof options.now==="function"?options.now:()=>globalThis.performance?.now?.()??Date.now();this.debugLastFrameTimeMs=null;
    this.debugKeyboardIntents=new Set();this.debugDomIntents=new Set();this.debugShiftActive=false;this.debugGuiSpeedMode="normal";this.debugCaptureMode="none";this.debugTouchToggle=null;this.debugTouchDrag=null;
    this.debugCaptureCursor=null;this.debugCaptureReleasePending=null;this.debugPointerLockRequest=null;this.debugReleaseListener=null;this.debugReleaseWaiters=[];
    this.gameplayAssetLoader=options.gameplayAssetLoader??new PlayCanvasGameplayAssetPreloader({fetch:options.fetch,baseUrl:options.gameplayAssetBaseUrl});this.gameplayAssetLoadPromise=null;
    this.environmentOwner=options.environmentOwner??new PlayCanvasEnvironmentAssetOwner({fetch:options.fetch,decodeImage:options.environmentDecodeImage,createSphere:options.environmentCreateSphere,locationHref:options.locationHref});this.environmentLoadPromise=null;
    this.onContextLost=(event)=>{event.preventDefault();this.resetProductionCameraParallax();this.contextLost=true;this.state="context_lost";this.atlasRestorePending=Boolean(this.iconAtlasData);this.iconTexture?.destroy();this.iconTexture=null;this.destroyInstantiatedPools();this.environmentOwner.handleContextLost();this.gameplayAssetLoader.handleContextLost();};
    this.onContextRestored=()=>{if(this.destroyed||!this.app)return;this.resetProductionCameraParallax();this.contextLost=false;this.contextRestoreCount+=1;this.state="ready";this.gameplayAssetLoadPromise=this.gameplayAssetLoader.preload(this.app);this.environmentLoadPromise=this.environmentOwner.restore(this.app);};
  }
  attach(canvas,options=this.contextAttributes){
    if(this.destroyed)return this.describe();
    if(this.canvas===canvas&&this.app)return this.describe();
    this.detach();this.canvas=canvas;this.contextAttributes=options;
    canvas.addEventListener("webglcontextlost",this.onContextLost);canvas.addEventListener("webglcontextrestored",this.onContextRestored);
    try{
      this.app=new pc.Application(canvas,{graphicsDeviceOptions:{...options,alpha:true}});
      this.app.scene.ambientLight=new pc.Color(0.85,0.88,0.95);
      this.app.scene.exposure=1;
      this.cameraEntity=new pc.Entity("aero-athlete-camera",this.app);
      this.cameraEntity.addComponent("camera",{clearColor:new pc.Color(0,0,0,0),clearColorBuffer:true,clearDepthBuffer:true,fov:defaultGameplayCameraPose.projection.verticalFovDegrees,nearClip:defaultGameplayCameraPose.projection.nearClip,farClip:defaultGameplayCameraPose.projection.farClip});
      this.app.root.addChild(this.cameraEntity);this.createGameplayLayers();this.resetDebugCamera();
      if(this.iconAtlasData)this.createAtlasTexture();
      this.app.requestAnimationFrame=()=>{};
      this.gameplayAssetLoadPromise=this.gameplayAssetLoader.preload(this.app);this.environmentLoadPromise=this.environmentOwner.attach(this.app);
      this.state="ready";this.errorMessage=null;
      if(this.widthCssPx||this.heightCssPx)this.applySize();
    }catch(error){this.fail(error);}
    return this.describe();
  }
  detach(){
    this.setDebugCameraEnabled(false);
    if(this.canvas){this.canvas.removeEventListener("webglcontextlost",this.onContextLost);this.canvas.removeEventListener("webglcontextrestored",this.onContextRestored);}
    this.destroyInstantiatedPools();this.environmentOwner.dispose();this.environmentLoadPromise=null;this.gameplayAssetLoader.dispose();this.gameplayAssetLoadPromise=null;for(const material of this.ownedMaterials)material.destroy();this.ownedMaterials.clear();this.materialStates=new WeakMap();
    const app=this.app;this.removeGameplayLayers();this.app=null;this.appStarted=false;this.cameraEntity=null;this.pool=[];this.assetPools=new Map();this.markerPool=[];this.markerPoolMode="none";this.feedbackPool=[];this.feedbackTextures=new Map();this.guidanceGlyphPool=[];this.guidanceGlyphTextures=new Map();this.guidanceHaloPool=[];this.overlayEntities=[];this.iconTexture=null;this.atlasRestorePending=false;this.activeCount=0;this.sceneDiagnostics=emptySceneDiagnostics();this.cursorDiagnostics=Object.freeze({instanceCount:0,assetId:"athlete-marker/sphere-v1",roles:Object.freeze([]),depthTest:true,depthWrite:true});
    if(app){try{app.destroy();}catch{}}
    this.canvas=null;this.contextLost=false;this.testPresentationConfig=defaultTestPresentationConfig;this.gameplayVisualExperimentConfig=defaultGameplayVisualExperimentConfig;this.resetProductionCameraParallax();effectiveMarkerPalettes.set(this,null);if(!this.destroyed)this.state="unsupported";return this.describe();
  }
  resize(size){if(!this.canvas||this.destroyed)return this.describe();this.widthCssPx=finiteNonNegative(size.widthCssPx);this.heightCssPx=finiteNonNegative(size.heightCssPx);const cap=Math.max(1,Math.min(size.maxDevicePixelRatio??this.tuning.dprCap,this.tuning.dprCap));this.devicePixelRatio=Math.max(0.1,Math.min(Number.isFinite(size.devicePixelRatio)?size.devicePixelRatio:1,cap));this.applySize();return this.describe();}
  applySize(){if(!this.canvas)return;const width=Math.max(1,Math.round(this.widthCssPx*this.devicePixelRatio)),height=Math.max(1,Math.round(this.heightCssPx*this.devicePixelRatio));this.canvas.style.width=`${this.widthCssPx}px`;this.canvas.style.height=`${this.heightCssPx}px`;this.canvas.width=width;this.canvas.height=height;if(this.app){this.app.setCanvasFillMode(pc.FILLMODE_NONE,this.widthCssPx,this.heightCssPx);this.app.setCanvasResolution(pc.RESOLUTION_FIXED,width,height);this.app.graphicsDevice.resizeCanvas(width,height);}}
  setTheme(descriptor){if(this.destroyed)return this.describe();const normalized=normalizeRendererTheme(descriptor);const accepted=isThemeDescriptor(descriptor)&&normalized!==defaultRendererThemeTokens;this.theme=normalized;this.themeId=accepted?descriptor.id:"aero.theme.default";this.themeVersion=accepted?descriptor.themeVersion:"1";this.themeHash=accepted?descriptor.contentHash.value:"theme-default";return this.describe();}
  setTuning(value){return this.importTuning(value);}
  importTuning(value){if(this.destroyed)return this.describe();this.visualProfile=normalizeRendererVisualProfile(value);this.tuning=rendererTuningFromVisualProfile(this.visualProfile);return this.describe();}
  resetTuning(){if(!this.destroyed){this.visualProfile=defaultRendererVisualProfile;this.tuning=rendererTuningFromVisualProfile(this.visualProfile);}return this.describe();}
  exportTuning(){return this.visualProfile;}
  setTestPresentationConfig(value){const normalized=normalizeTestPresentationConfig(value);if(this.destroyed)return this.describe();this.testPresentationConfig=normalized;return this.describe();}
  resetTestPresentationConfig(){if(!this.destroyed)this.testPresentationConfig=defaultTestPresentationConfig;return this.describe();}
  setGameplayVisualExperimentConfig(value){const normalized=normalizeGameplayVisualExperimentConfig(value);if(!this.destroyed){this.gameplayVisualExperimentConfig=normalized;this.resetProductionCameraParallax();}return this.describe();}
  resetGameplayVisualExperimentConfig(){if(!this.destroyed){this.gameplayVisualExperimentConfig=defaultGameplayVisualExperimentConfig;this.resetProductionCameraParallax();}return this.describe();}
  getSnapshot(){return this.describe();}
  setBackgroundProjection(value){if(!this.destroyed)this.background=normalizeBackgroundProjection(value);return this.describe();}
  setEnvironmentAsset(descriptor){if(this.destroyed)return this.describe();this.environmentLoadPromise=this.environmentOwner.setDescriptor(descriptor);return this.describe();}
  setEnvironmentTransform(transform){if(!this.destroyed)this.environmentOwner.setTransform(transform);return this.describe();}
  setEnvironmentVisible(visible){if(!this.destroyed)this.environmentOwner.setVisible(visible);return this.describe();}
  uploadIconAtlas(atlas){if(this.destroyed)return this.describe();try{this.iconAtlasData=normalizeIconAtlasData(atlas);this.iconEntries=new Map(this.iconAtlasData.entries.map((entry)=>[entry.id,entry]));this.iconAtlasError=null;if(this.app)this.createAtlasTexture();}catch(error){this.iconAtlasData=null;this.iconEntries.clear();this.iconTexture?.destroy();this.iconTexture=null;this.iconAtlasError=error instanceof Error?error.message:"Icon atlas is invalid";}return this.describe();}
  createAtlasTexture(){if(!this.app||!this.iconAtlasData)return;this.iconTexture?.destroy();const atlas=this.iconAtlasData;const texture=new pc.Texture(this.app.graphicsDevice,{name:"aero-icon-atlas",width:atlas.width,height:atlas.height,format:pc.PIXELFORMAT_RGBA8,mipmaps:false,minFilter:pc.FILTER_LINEAR,magFilter:pc.FILTER_LINEAR,addressU:pc.ADDRESS_CLAMP_TO_EDGE,addressV:pc.ADDRESS_CLAMP_TO_EDGE});const pixels=texture.lock();pixels.set(atlas.pixels);texture.unlock();this.iconTexture=texture;}
  renderGameplayFrame(frame){return this.renderGameplayScene(frame,null,null);}
  renderGameplayFrameWithCursors(frame,cursors,options){return this.renderGameplayScene(frame,cursors,options);}
  renderGameplayScene(frame,cursors,cursorOptions){this.integrateDebugCameraMotion();const model=buildGameplaySceneModel(frame,this.theme,this.tuning,this.testPresentationConfig,this.gameplayVisualExperimentConfig),cameraDeflection=normalizeCameraDeflection(frame?.cameraDeflection??null);if(this.app&&!this.destroyed&&!this.contextLost)this.updateProductionCameraParallax(cameraDeflection);else this.resetProductionCameraParallax();this.lastModel=model;if(this.gameplayAssetLoader.describe().state==="error")this.gameplayAssetLoader.activateFallback("preload_error");if(!this.app||this.destroyed||this.contextLost)return{status:this.describe(),model,...(cursors===null?{}:{cursorCount:0,roles:Object.freeze([])})};try{this.clearOverlayEntities();this.applyCamera(model);this.updateSceneObjects(model.objects);this.applyClearColor();const cursorResult=cursors===null?null:this.stageGameplayCursors(cursors,cursorOptions,false);this.manualTick();this.frameCount+=1;this.drawCount+=model.objects.length+(cursorResult?.cursorCount??0);this.state="running";return{status:this.describe(),model,...(cursorResult??{})};}catch(error){this.fail(error);return{status:this.describe(),model,...(cursors===null?{}:{cursorCount:0,roles:Object.freeze([])})};}}
  clear(options={}){if(!this.app||this.destroyed)return{status:this.describe()};const color=options.color??[0,0,0,0];this.cameraEntity.camera.clearColor=new pc.Color(...color);this.clearSceneObjects();this.clearOverlayEntities();this.manualTick();this.frameCount+=1;this.state="running";return{status:this.describe()};}
  renderFrame(options={}){return this.clear(options);}
  renderGameplayCursors(cursors,options){const result=this.stageGameplayCursors(cursors,options,true);if(!this.app||this.destroyed||this.contextLost)return Object.freeze({status:this.describe(),cursorCount:0,roles:Object.freeze([])});this.manualTick();this.drawCount+=result.cursorCount;this.state="running";return Object.freeze({status:this.describe(),...result});}
  stageGameplayCursors(cursors,options,clear){normalizeCursorGrid(options?.grid);if(!Array.isArray(cursors)||cursors.length>12)throw new TypeError("Gameplay cursors cannot exceed 12 candidates");const min=Math.max(0,Math.min(1,Number.isFinite(options?.minConfidence)?options.minConfidence:0.5));const accepted=new Map();for(const cursor of cursors){if(!plainData(cursor)||Object.keys(cursor).length!==4||!cursorRoles.includes(cursor.role)||accepted.has(cursor.role)||![cursor.x,cursor.y,cursor.confidence].every(Number.isFinite)||cursor.x<0||cursor.x>1||cursor.y<0||cursor.y>1||cursor.confidence<min)continue;accepted.set(cursor.role,cursor);}
    if(!this.app||this.destroyed||this.contextLost)return Object.freeze({cursorCount:0,roles:Object.freeze([])});
    if(clear)this.clearOverlayEntities();for(const entity of this.markerPool)entity.enabled=false;const roles=[];if(this.gameplayAssetLoader.describe().state==="error")this.gameplayAssetLoader.activateFallback("preload_error");const mode=this.gameplayAssetLoader.describe().state;
    const sizeCssPx=clamp(Number.isFinite(options?.sizeCssPx)?Number(options.sizeCssPx):18,8,64),markerScales=[];
    const effectivePalette=effectiveMarkerPalettes.get(this);for(const role of cursorRoles){const cursor=accepted.get(role);if(!cursor)continue;const position=gridPositionForNormalized(cursor.x,cursor.y,0.45),color=role==="nose"?"#f4c20d":role==="left_wrist"?(effectivePalette?.left??this.theme.leftHandColor):(effectivePalette?.right??this.theme.rightHandColor);let entity=null;if(mode==="ready")entity=this.acquireMarkerEntity(roles.length);else if(mode==="fallback")entity=this.acquireFallbackMarker(roles.length);if(!entity)continue;const worldScale=this.worldScaleForCssPx(sizeCssPx,position,mode==="ready"?.18:1);entity.enabled=true;entity.name=`cursor-${role}`;entity.setPosition(position.x,position.y,position.z);entity.setLocalScale(worldScale,worldScale,worldScale);entity.setEulerAngles(0,0,0);if(mode==="ready")this.applyAssetAppearance(entity,"athlete-marker/sphere-v1",color,1,false);else this.updateMaterial(entity,color,1,null,false,true);roles.push(role);markerScales.push(worldScale);}
    this.cursorDiagnostics=Object.freeze({instanceCount:roles.length,assetId:"athlete-marker/sphere-v1",roles:Object.freeze([...roles]),depthTest:true,depthWrite:true,sourceMode:mode,sizeCssPx,worldScales:Object.freeze(markerScales)});return Object.freeze({cursorCount:roles.length,roles:Object.freeze(roles)});
  }
  renderLandmarkOverlay(landmarks,options={}){if(!this.app||this.destroyed||this.contextLost)return{status:this.describe(),pointCount:0,lineVertexCount:0};this.clearOverlayEntities();const surface=normalizeOverlaySurfaceDescriptor({viewportWidth:this.canvas.width,viewportHeight:this.canvas.height,...options.surface});const min=options.minVisibility??0;const visible=landmarks.filter((entry)=>(typeof entry.v==="number"?entry.v:1)>=min);const byId=new Map(visible.map((entry)=>[entry.id,entry]));const color=rgbaToHex(options.color??[0.24,0.9,0.45,0.95]);for(const landmark of visible){const p=mapNormalizedLandmarkToViewport(landmark,surface);const position=gridPositionForNormalized(p.x/surface.viewportWidth,p.y/surface.viewportHeight,0.42);this.addOverlayDisc(`landmark-${landmark.id??this.overlayEntities.length}`,position.x,position.y,position.z,(options.pointSize??6)/42,color);}let lines=0;for(const [aId,bId] of options.connections??[]){const a=byId.get(aId),b=byId.get(bId);if(!a||!b)continue;const ap=mapNormalizedLandmarkToViewport(a,surface),bp=mapNormalizedLandmarkToViewport(b,surface);this.addOverlayLine(ap,bp,surface,color);lines+=2;}this.manualTick();this.drawCount+=visible.length+lines/2;this.state="running";return{status:this.describe(),pointCount:visible.length,lineVertexCount:lines};}
  setDebugCameraEnabled(enabled){
    const next=Boolean(enabled)&&!this.destroyed&&Boolean(this.canvas)&&Boolean(this.app);if(this.debugEnabled===next)return this.describe();
    if(!next){this.clearDebugInteractionState(true);this.debugEnabled=false;this.removeDebugListeners();this.resetProductionCameraParallax();this.resetDebugCamera();return this.describe();}
    this.removeDebugListeners();this.clearDebugInteractionState(true);this.resetProductionCameraParallax();this.debugEnabled=true;
    const canvas=this.canvas;const on=(target,type,listener,options)=>{target.addEventListener(type,listener,options);this.debugListeners.push(()=>target.removeEventListener(type,listener,options));};
    on(canvas,"contextmenu",(event)=>event.preventDefault());
    on(canvas,"mousedown",(event)=>{if(event.button!==2)return;event.preventDefault();if(this.debugCaptureReleasePending)return;if(this.debugCaptureMode!=="none")this.exitDebugCapture(true);else this.enterDebugPointerCapture();});
    on(document,"pointerlockchange",()=>this.handleDebugPointerLockChange(canvas));
    on(document,"pointerlockerror",()=>this.handleDebugPointerLockError(canvas));
    on(document,"mousemove",(event)=>{if(!this.debugEnabled||this.debugCaptureReleasePending||!debugMouseCaptureModes.includes(this.debugCaptureMode))return;this.applyDebugLookDelta(event.movementX,event.movementY,0.0025);});
    on(window,"keydown",(event)=>{if(!this.debugEnabled)return;if(event.code==="Escape"&&this.debugCaptureMode!=="none"){event.preventDefault();this.exitDebugCapture(true);return;}if(event.code==="ShiftLeft"||event.code==="ShiftRight"){this.debugShiftActive=true;event.preventDefault();return;}const intent=debugKeyIntents[event.code];if(!intent)return;this.debugKeyboardIntents.add(intent);event.preventDefault();});
    on(window,"keyup",(event)=>{if(event.code==="ShiftLeft"||event.code==="ShiftRight"){this.debugShiftActive=false;return;}const intent=debugKeyIntents[event.code];if(intent)this.debugKeyboardIntents.delete(intent);});
    on(window,"blur",()=>this.clearDebugInteractionState(true));
    on(document,"visibilitychange",()=>{if(document.visibilityState==="hidden")this.clearDebugInteractionState(true);});
    on(canvas,"touchstart",(event)=>this.onDebugTouchStart(event),{passive:false});
    on(canvas,"touchmove",(event)=>this.onDebugTouchMove(event),{passive:false});
    on(canvas,"touchend",(event)=>this.onDebugTouchEnd(event),{passive:false});
    on(canvas,"touchcancel",(event)=>this.onDebugTouchCancel(event),{passive:false});
    return this.describe();
  }
  setDebugCameraMovementIntent(intent,active){if(!debugMovementIntents.includes(intent))throw new TypeError(`Unknown debug camera movement intent: ${String(intent)}`);if(typeof active!=="boolean")throw new TypeError("Debug camera movement intent active state must be boolean");if(!this.debugEnabled||this.destroyed)return this.describe();if(active)this.debugDomIntents.add(intent);else this.debugDomIntents.delete(intent);return this.describe();}
  setDebugCameraSpeedMode(mode){if(!debugSpeedModes.includes(mode))throw new TypeError(`Unknown debug camera speed mode: ${String(mode)}`);if(!this.debugEnabled||this.destroyed)return this.describe();this.debugGuiSpeedMode=mode;return this.describe();}
  releaseDebugCameraAuthoringInput(){if(this.debugEnabled&&!this.destroyed)this.clearDebugInteractionState(true);return this.describe();}
  /** Strictly normalize unknown v1 data and apply it only to the live rendered debug camera after authoring input is released. @param {unknown} value */
  async loadDebugCameraPose(value){
    const pose=normalizeGameplayCameraPose(value),canvas=this.canvas,app=this.app,cameraEntity=this.cameraEntity;
    this.assertDebugCameraPoseAuthoringReady("load");
    this.clearDebugInteractionState(true);
    await this.waitForDebugCaptureRelease();
    if(canvas!==this.canvas||app!==this.app||cameraEntity!==this.cameraEntity)throw new Error("Debug camera pose load became stale");
    this.assertDebugCameraPoseAuthoringReady("load",true);
    this.debugPosition={...pose.position};this.debugPitch=pose.rotationEulerDegrees.xPitch*Math.PI/180;this.debugYaw=pose.rotationEulerDegrees.yYaw*Math.PI/180;this.debugProjection={...pose.projection};this.debugLastFrameTimeMs=null;this.applyPose(pose);
    return pose;
  }
  enterDebugPointerCapture(){
    if(!this.debugEnabled||!this.canvas||this.debugCaptureReleasePending||this.debugCaptureMode!=="none")return;const canvas=this.canvas;this.captureDebugCursor(canvas);this.debugCaptureMode="fallback";
    try{const pending=canvas.requestPointerLock?.();if(pending&&typeof pending.then==="function"){const request={canvas,promise:pending};this.debugPointerLockRequest=request;pending.then(()=>{if(this.debugPointerLockRequest===request)this.debugPointerLockRequest=null;if(this.debugCaptureReleasePending||!this.debugEnabled||this.destroyed)this.exitDebugCapture(true);}).catch(()=>{if(this.debugPointerLockRequest===request)this.debugPointerLockRequest=null;if(this.debugCaptureReleasePending)this.finalizeDebugCapture(canvas);});}}
    catch{this.debugPointerLockRequest=null;/* bounded fallback remains active */}
  }
  exitDebugCapture(exitPointerLock){
    const canvas=this.debugCaptureCursor?.canvas??this.canvas;if(!canvas){this.finalizeDebugCapture(null);return;}
    const locked=exitPointerLock&&typeof document!=="undefined"&&document.pointerLockElement===canvas,pendingRequest=this.debugPointerLockRequest?.canvas===canvas;
    if(locked||pendingRequest){if(!this.debugCaptureReleasePending){this.debugCaptureReleasePending={canvas};this.installDebugReleaseListener();}if(locked){try{document.exitPointerLock?.();}catch{this.finalizeDebugCapture(canvas);}}return;}
    this.finalizeDebugCapture(canvas);
  }
  handleDebugPointerLockChange(canvas){
    if(typeof document==="undefined")return;const locked=document.pointerLockElement===canvas;
    if(locked){if(this.debugCaptureMode==="none"||this.debugCaptureReleasePending||!this.debugEnabled||this.destroyed){if(!this.debugCaptureReleasePending){this.debugCaptureReleasePending={canvas};this.installDebugReleaseListener();}try{document.exitPointerLock?.();}catch{this.finalizeDebugCapture(canvas);}return;}if(this.debugCaptureMode!=="none"){this.debugCaptureMode="pointer";this.applyCapturedDebugCursor(canvas);}return;}
    if(this.debugCaptureReleasePending?.canvas===canvas||this.debugCaptureMode==="pointer")this.finalizeDebugCapture(canvas);
  }
  handleDebugPointerLockError(canvas){if(typeof document!=="undefined"&&document.pointerLockElement===canvas)return;if(this.debugCaptureReleasePending?.canvas===canvas)this.finalizeDebugCapture(canvas);else if(this.debugCaptureMode==="pointer")this.debugCaptureMode="fallback";}
  captureDebugCursor(canvas){if(this.debugCaptureCursor?.canvas!==canvas){const inline=canvas.style?.cursor??"",computed=typeof getComputedStyle==="function"?getComputedStyle(canvas).cursor:inline||"default";this.debugCaptureCursor={canvas,inline,computed};}this.applyCapturedDebugCursor(canvas);}
  applyCapturedDebugCursor(canvas){if(canvas.style)canvas.style.cursor="none";}
  restoreDebugCursor(canvas){const snapshot=this.debugCaptureCursor;if(!snapshot||snapshot.canvas!==canvas)return;if(canvas.style)canvas.style.cursor=snapshot.inline;const restored=typeof getComputedStyle==="function"?getComputedStyle(canvas).cursor:canvas.style?.cursor;if(canvas.style&&restored==="none"&&snapshot.computed!=="none")canvas.style.cursor=snapshot.computed||"default";this.debugCaptureCursor=null;}
  finalizeDebugCapture(canvas){this.debugCaptureMode="none";this.debugTouchToggle=null;this.debugTouchDrag=null;this.debugCaptureReleasePending=null;if(canvas)this.restoreDebugCursor(canvas);this.removeDebugReleaseListener();for(const resolve of this.debugReleaseWaiters.splice(0))resolve();}
  waitForDebugCaptureRelease(){if(!this.debugCaptureReleasePending&&!this.debugPointerLockRequest&&this.debugCaptureMode==="none"&&(!this.canvas||typeof document==="undefined"||document.pointerLockElement!==this.canvas))return Promise.resolve();return new Promise((resolve)=>this.debugReleaseWaiters.push(resolve));}
  installDebugReleaseListener(){if(this.debugReleaseListener||typeof document==="undefined")return;const listener=()=>{const pending=this.debugCaptureReleasePending;if(pending)this.handleDebugPointerLockChange(pending.canvas);};document.addEventListener("pointerlockchange",listener);this.debugReleaseListener=()=>document.removeEventListener("pointerlockchange",listener);}
  removeDebugReleaseListener(){const remove=this.debugReleaseListener;this.debugReleaseListener=null;remove?.();}
  clearDebugInteractionState(exitPointerLock){this.debugKeyboardIntents.clear();this.debugDomIntents.clear();this.debugShiftActive=false;this.debugLastFrameTimeMs=null;this.exitDebugCapture(exitPointerLock);}
  applyDebugLookDelta(deltaX,deltaY,sensitivity){if(!Number.isFinite(deltaX)||!Number.isFinite(deltaY))return;this.debugYaw=normalizeRadians(this.debugYaw-deltaX*sensitivity);this.debugPitch=clamp(this.debugPitch-deltaY*sensitivity,-1.35,1.35);this.applyDebugPose();}
  onDebugTouchStart(event){
    if(!this.debugEnabled)return;const touches=Array.from(event.touches);
    if(touches.length===2){this.debugTouchDrag=null;this.debugTouchToggle={startedAt:event.timeStamp,points:new Map(touches.map((touch)=>[touch.identifier,{x:touch.clientX,y:touch.clientY}])),moved:false,maxTouches:2};if(this.debugCaptureMode==="touch")event.preventDefault();return;}
    if(touches.length===1&&this.debugCaptureMode==="touch"){const touch=touches[0];this.debugTouchToggle=null;this.debugTouchDrag={identifier:touch.identifier,x:touch.clientX,y:touch.clientY};event.preventDefault();return;}
    if(touches.length>2){this.debugTouchToggle=null;this.debugTouchDrag=null;if(this.debugCaptureMode==="touch")event.preventDefault();}
  }
  onDebugTouchMove(event){
    if(!this.debugEnabled)return;const touches=Array.from(event.touches),toggle=this.debugTouchToggle;
    if(toggle){toggle.maxTouches=Math.max(toggle.maxTouches,touches.length);if(touches.length!==2)toggle.moved=true;for(const touch of touches){const start=toggle.points.get(touch.identifier);if(!start||Math.hypot(touch.clientX-start.x,touch.clientY-start.y)>DEBUG_TOUCH_TAP_MAX_MOVE_PX)toggle.moved=true;}if(this.debugCaptureMode==="touch")event.preventDefault();return;}
    const drag=this.debugTouchDrag;if(this.debugCaptureMode!=="touch"||!drag)return;const touch=touches.find((entry)=>entry.identifier===drag.identifier);if(!touch){this.debugTouchDrag=null;return;}const deltaX=touch.clientX-drag.x,deltaY=touch.clientY-drag.y;drag.x=touch.clientX;drag.y=touch.clientY;this.applyDebugLookDelta(deltaX,deltaY,0.006);event.preventDefault();
  }
  onDebugTouchEnd(event){
    if(!this.debugEnabled)return;const wasTouchCaptured=this.debugCaptureMode==="touch",toggle=this.debugTouchToggle;if(wasTouchCaptured)event.preventDefault();
    if(toggle&&event.touches.length===0){const duration=event.timeStamp-toggle.startedAt,valid=toggle.maxTouches===2&&!toggle.moved&&duration>=0&&duration<=DEBUG_TOUCH_TAP_MAX_MS;this.debugTouchToggle=null;if(valid){if(wasTouchCaptured)this.exitDebugCapture(true);else if(!this.debugCaptureReleasePending){this.exitDebugCapture(true);if(!this.debugCaptureReleasePending)this.debugCaptureMode="touch";}}}
    if(this.debugTouchDrag&&!Array.from(event.touches).some((touch)=>touch.identifier===this.debugTouchDrag.identifier))this.debugTouchDrag=null;
  }
  onDebugTouchCancel(event){if(this.debugCaptureMode==="touch")event.preventDefault();this.debugTouchToggle=null;this.debugTouchDrag=null;}
  integrateDebugCameraMotion(){
    if(!this.debugEnabled){this.debugLastFrameTimeMs=null;return;}const now=Number(this.debugNow());if(!Number.isFinite(now)){this.debugLastFrameTimeMs=null;return;}const previous=this.debugLastFrameTimeMs;this.debugLastFrameTimeMs=now;if(previous===null)return;const deltaSeconds=clamp(now-previous,0,DEBUG_MAX_DELTA_MS)/1000;if(deltaSeconds===0)return;
    const active=new Set([...this.debugKeyboardIntents,...this.debugDomIntents]),forward=(active.has("forward")?1:0)-(active.has("back")?1:0),right=(active.has("right")?1:0)-(active.has("left")?1:0),vertical=(active.has("up")?1:0)-(active.has("down")?1:0);let planarForward=forward,planarRight=right;const planarLength=Math.hypot(planarForward,planarRight);if(planarLength>1){planarForward/=planarLength;planarRight/=planarLength;}const sin=Math.sin(this.debugYaw),cos=Math.cos(this.debugYaw);let x=-sin*planarForward+cos*planarRight,z=-cos*planarForward-sin*planarRight,y=vertical;const totalLength=Math.hypot(x,y,z);if(totalLength>1){x/=totalLength;y/=totalLength;z/=totalLength;}const speed=(this.debugShiftActive||this.debugGuiSpeedMode==="boost")?DEBUG_BOOST_UNITS_PER_SECOND:DEBUG_NORMAL_UNITS_PER_SECOND;this.debugPosition.x=clamp(this.debugPosition.x+x*speed*deltaSeconds,-DEBUG_POSITION_BOUNDS.x,DEBUG_POSITION_BOUNDS.x);this.debugPosition.y=clamp(this.debugPosition.y+y*speed*deltaSeconds,DEBUG_POSITION_BOUNDS.yMin,DEBUG_POSITION_BOUNDS.yMax);this.debugPosition.z=clamp(this.debugPosition.z+z*speed*deltaSeconds,DEBUG_POSITION_BOUNDS.zMin,DEBUG_POSITION_BOUNDS.zMax);this.applyDebugPose();
  }
  resetDebugCamera(){this.debugYaw=defaultGameplayCameraPose.rotationEulerDegrees.yYaw*Math.PI/180;this.debugPitch=defaultGameplayCameraPose.rotationEulerDegrees.xPitch*Math.PI/180;this.debugPosition={...defaultGameplayCameraPose.position};this.debugProjection={...defaultGameplayCameraPose.projection};this.debugLastFrameTimeMs=null;this.applyPose(defaultGameplayCameraPose);return this.describe();}
  assertDebugCameraPoseAuthoringReady(operation,requireReleased=false){
    const released=this.debugCaptureMode==="none"&&!this.debugCaptureReleasePending&&!this.debugPointerLockRequest&&!this.debugKeyboardIntents.size&&!this.debugDomIntents.size&&!this.debugShiftActive&&!this.debugTouchToggle&&!this.debugTouchDrag&&(!this.canvas||typeof document==="undefined"||document.pointerLockElement!==this.canvas);
    if(!this.debugEnabled||!this.canvas||!this.app||!this.cameraEntity||this.destroyed||this.contextLost||this.frameCount<1||(requireReleased&&!released))throw new Error(`Debug camera pose ${operation} requires an active rendered debug camera${requireReleased?" with no capture or movement input":""}`);
  }
  exportDebugCameraPoseArtifact(){
    this.assertDebugCameraPoseAuthoringReady("export",true);
    const position=this.cameraEntity.getPosition(),camera=this.cameraEntity.camera;
    const data=normalizeGameplayCameraPose({schema:defaultGameplayCameraPose.schema,version:defaultGameplayCameraPose.version,coordinateSystem:{...defaultGameplayCameraPose.coordinateSystem},position:{x:position.x,y:position.y,z:position.z},rotationEulerDegrees:{xPitch:this.debugPitch*180/Math.PI,yYaw:this.debugYaw*180/Math.PI,zRoll:0},projection:{verticalFovDegrees:camera.fov,nearClip:camera.nearClip,farClip:camera.farClip}});
    this.debugPosition={...data.position};this.debugPitch=data.rotationEulerDegrees.xPitch*Math.PI/180;this.debugYaw=data.rotationEulerDegrees.yYaw*Math.PI/180;this.debugProjection={...data.projection};this.applyPose(data);
    const json=serializeGameplayCameraPose(data),bytes=Object.freeze(Array.from(new TextEncoder().encode(json)));
    return Object.freeze({filename:gameplayCameraPoseArtifactFilename,mimeType:gameplayCameraPoseArtifactMimeType,data,json,bytes});
  }
  removeDebugListeners(){for(const remove of this.debugListeners.splice(0))remove();}
  resetProductionCameraParallax(){const state=productionCameraStates.get(this);if(state){state.offset={x:0,y:0};state.lastTimeMs=null;}if(this.cameraEntity&&!this.debugEnabled)this.applyPose(defaultGameplayCameraPose);}
  updateProductionCameraParallax(value){
    const desired=normalizeCameraDeflection(value),config=this.gameplayVisualExperimentConfig,state=productionCameraStates.get(this);if(!state)return;const now=Number(this.productionCameraNow());if(!Number.isFinite(now)){this.resetProductionCameraParallax();return;}
    const previous=state.lastTimeMs;state.lastTimeMs=now;if(previous===null)return;const deltaMs=clamp(now-previous,0,PRODUCTION_CAMERA_MAX_DELTA_MS);if(deltaMs<=0)return;
    const active=!this.debugEnabled&&config.noseCameraParallax&&desired.active,deadzone=config.deadzoneNormalized;
    const normalizedX=active?applyAxialDeadzone(desired.xDeflection,deadzone):0,normalizedY=active?applyAxialDeadzone(desired.yDeflection,deadzone):0;
    const targetX=normalizedX*config.horizontalRangeWorldUnits,targetY=-normalizedY*config.verticalRangeWorldUnits,tau=active?config.smoothingTimeConstantMs:config.recenterTimeConstantMs,alpha=tau===0?1:1-Math.exp(-deltaMs/tau),maxX=config.maximumHorizontalVelocityWorldUnitsPerSecond*deltaMs/1000,maxY=config.maximumVerticalVelocityWorldUnitsPerSecond*deltaMs/1000;
    state.offset={x:moveToward(state.offset.x,state.offset.x+(targetX-state.offset.x)*alpha,maxX),y:moveToward(state.offset.y,state.offset.y+(targetY-state.offset.y)*alpha,maxY)};
  }
  applyPose(pose){if(!this.cameraEntity)return;const position=pose.position,rotation=pose.rotationEulerDegrees,projection=pose.projection;this.cameraEntity.setPosition(position.x,position.y,position.z);this.cameraEntity.setEulerAngles(rotation.xPitch,rotation.yYaw,rotation.zRoll);this.cameraEntity.camera.fov=projection.verticalFovDegrees;this.cameraEntity.camera.nearClip=projection.nearClip;this.cameraEntity.camera.farClip=projection.farClip;this.syncEnvironmentAnchor();}
  syncEnvironmentAnchor(){const position=this.cameraEntity?.getPosition();if(position)this.environmentOwner.setCameraPosition(position);}
  applyDebugPose(){if(!this.cameraEntity)return;this.applyPose(normalizeGameplayCameraPose({schema:defaultGameplayCameraPose.schema,version:defaultGameplayCameraPose.version,coordinateSystem:{...defaultGameplayCameraPose.coordinateSystem},position:{...this.debugPosition},rotationEulerDegrees:{xPitch:this.debugPitch*180/Math.PI,yYaw:this.debugYaw*180/Math.PI,zRoll:0},projection:{...this.debugProjection}}));}
  applyCamera(model){if(!this.cameraEntity)return;if(this.debugEnabled){this.applyDebugPose();return;}const camera=model.camera,offset=productionCameraStates.get(this)?.offset??{x:0,y:0};this.applyPose({...camera,position:{x:camera.position.x+offset.x,y:camera.position.y+offset.y,z:camera.position.z}});}
  createGameplayLayers(){
    if(!this.app||!this.cameraEntity?.camera)return;const composition=this.app.scene.layers,world=composition.getLayerById(pc.LAYERID_WORLD);if(!world)throw new Error("PlayCanvas World layer is unavailable");
    const gridLayer=new pc.Layer({name:"Aero Gameplay Grid",clearColorBuffer:false,clearDepthBuffer:false,clearStencilBuffer:false,opaqueSortMode:pc.SORTMODE_MANUAL,transparentSortMode:pc.SORTMODE_MANUAL}),guidanceUnderLayer=new pc.Layer({name:"Aero Gameplay Guidance Under",clearColorBuffer:false,clearDepthBuffer:false,clearStencilBuffer:false,opaqueSortMode:pc.SORTMODE_MANUAL,transparentSortMode:pc.SORTMODE_MANUAL}),targetLayer=new pc.Layer({name:"Aero Gameplay Targets",clearColorBuffer:false,clearDepthBuffer:false,clearStencilBuffer:false,opaqueSortMode:pc.SORTMODE_FRONT2BACK,transparentSortMode:pc.SORTMODE_BACK2FRONT}),guidanceOverLayer=new pc.Layer({name:"Aero Gameplay Guidance Over",clearColorBuffer:false,clearDepthBuffer:false,clearStencilBuffer:false,opaqueSortMode:pc.SORTMODE_MANUAL,transparentSortMode:pc.SORTMODE_MANUAL});
    const worldTransparentIndex=composition.getTransparentIndex(world);if(worldTransparentIndex<0)throw new Error("PlayCanvas World transparent layer is unavailable");composition.insertTransparent(gridLayer,worldTransparentIndex);composition.insertTransparent(guidanceUnderLayer,worldTransparentIndex+1);composition.insert(targetLayer,worldTransparentIndex+2);composition.insertTransparent(guidanceOverLayer,worldTransparentIndex+3);this.gameplayGridLayer=gridLayer;this.gameplayGuidanceUnderLayer=guidanceUnderLayer;this.gameplayTargetLayer=targetLayer;this.gameplayGuidanceOverLayer=guidanceOverLayer;this.cameraEntity.camera.layers=[...this.cameraEntity.camera.layers,gridLayer.id,guidanceUnderLayer.id,targetLayer.id,guidanceOverLayer.id];
  }
  removeGameplayLayers(){const gridLayer=this.gameplayGridLayer,guidanceUnderLayer=this.gameplayGuidanceUnderLayer,targetLayer=this.gameplayTargetLayer,guidanceOverLayer=this.gameplayGuidanceOverLayer;this.gameplayGridLayer=null;this.gameplayGuidanceUnderLayer=null;this.gameplayTargetLayer=null;this.gameplayGuidanceOverLayer=null;if(this.cameraEntity?.camera)this.cameraEntity.camera.layers=this.cameraEntity.camera.layers.filter((id)=>![gridLayer?.id,guidanceUnderLayer?.id,targetLayer?.id,guidanceOverLayer?.id].includes(id));if(gridLayer)this.app?.scene.layers.removeTransparent(gridLayer);if(guidanceUnderLayer)this.app?.scene.layers.removeTransparent(guidanceUnderLayer);if(targetLayer)this.app?.scene.layers.remove(targetLayer);if(guidanceOverLayer)this.app?.scene.layers.removeTransparent(guidanceOverLayer);}
  useGameplayLayer(entity,kind){const layerId=kind==="grid"?this.gameplayGridLayer?.id:kind==="guidance_under"?this.gameplayGuidanceUnderLayer?.id:kind==="target"?this.gameplayTargetLayer?.id:kind==="guidance_over"?this.gameplayGuidanceOverLayer?.id:pc.LAYERID_WORLD;for(const component of entity.findComponents?.("render")??[])component.layers=[layerId??pc.LAYERID_WORLD];}
  updateSceneObjects(objects){
    const loader=this.gameplayAssetLoader.describe(),mode=loader.state;if(mode==="ready"&&this.assetPoolGeneration!==loader.generation){this.destroyInstantiatedPools();this.assetPoolGeneration=loader.generation;}
    for(const entity of this.pool)entity.enabled=false;for(const entries of this.assetPools.values())for(const entity of entries)entity.enabled=false;for(const entry of this.feedbackPool)entry.root.enabled=false;for(const entry of this.guidanceGlyphPool)entry.root.enabled=false;for(const entry of this.guidanceHaloPool)entry.root.enabled=false;
    const assetCounts=new Map(),renderedCounts=new Map();let primitiveIndex=0,feedbackIndex=0,guidanceGlyphIndex=0,guidanceHaloIndex=0,fallbackCount=0,drawIndex=0;
    for(const object of objects){let entity=null;if(object.kind==="feedback"){entity=this.acquireFeedbackEntity(feedbackIndex++,object);if(entity)this.applyDrawOrder(entity,object.renderOrder*100+drawIndex++);if(entity)renderedCounts.set("world-feedback",(renderedCounts.get("world-feedback")??0)+1);continue;}if(object.kind==="guidance_halo"){entity=this.acquireGuidanceHaloEntity(guidanceHaloIndex++,object);if(entity)this.applyDrawOrder(entity,object.renderOrder*100+drawIndex++);if(entity)renderedCounts.set("guidance-halo",(renderedCounts.get("guidance-halo")??0)+1);continue;}if(object.kind==="guidance_number_glyph"){entity=this.acquireGuidanceGlyphEntity(guidanceGlyphIndex++,object);if(entity)this.applyDrawOrder(entity,object.renderOrder*100+drawIndex++);if(entity)renderedCounts.set("guidance-number-glyph",(renderedCounts.get("guidance-number-glyph")??0)+1);continue;}if(object.assetId){if(mode==="ready"){const index=assetCounts.get(object.assetId)??0;entity=this.acquireAssetEntity(object.assetId,index);assetCounts.set(object.assetId,index+1);}else if(mode==="fallback"){entity=this.acquirePrimitiveEntity(primitiveIndex++);fallbackCount+=1;}}else entity=this.acquirePrimitiveEntity(primitiveIndex++);if(!entity)continue;this.useGameplayLayer(entity,object.kind==="cell"||object.kind==="lane"||object.kind==="timing"?"grid":object.kind==="guidance_ribbon"||object.kind==="guidance_halo"?"guidance_under":object.kind==="icon"?"target":object.kind==="guidance_number_plate"?"guidance_over":"world");entity.enabled=true;entity.name=object.id;entity.setPosition(object.position.x,object.position.y,object.position.z);if(object.kind==="guidance_number_plate"){const height=this.worldScaleForCssPx(28,object.position);entity.setLocalScale(height*1.8,height,.025);}else entity.setLocalScale(object.scale.x,object.scale.y,object.scale.z);entity.setEulerAngles(0,0,object.rotationZRad*180/Math.PI);if((object.kind==="guidance_halo"||object.kind==="guidance_number_plate")&&this.cameraEntity)entity.setRotation(this.cameraEntity.getRotation());this.applyDrawOrder(entity,object.renderOrder*100+drawIndex++);const appearance=object.appearanceColor??this.roleColor(object.role);if(object.assetId&&mode==="ready"){const color=mixColorTokens(appearance,"#ffffff",object.tintMix);this.applyAssetAppearance(entity,object.assetId,color,object.alpha,object.kind==="obstacle"&&object.tintMix>0);renderedCounts.set(object.assetId,(renderedCounts.get(object.assetId)??0)+1);}else this.updateMaterial(entity,appearance,object.alpha,null,object.state==="spent",false);}
    this.activeCount=[...renderedCounts.values()].reduce((sum,value)=>sum+value,0)+primitiveIndex;this.sceneDiagnostics=buildSceneDiagnostics(objects,mode,loader,renderedCounts,fallbackCount);
  }
  acquirePrimitiveEntity(index){while(this.pool.length<=index)this.pool.push(this.makeEntity(`pooled-${this.pool.length}`,"box"));return this.pool[index];}
  acquireAssetEntity(assetId,index){let entries=this.assetPools.get(assetId);if(!entries){entries=[];this.assetPools.set(assetId,entries);}while(entries.length<=index){const resource=this.gameplayAssetLoader.resourceFor(assetId);if(!resource?.instantiateRenderEntity)return null;const entity=resource.instantiateRenderEntity({castShadows:false,receiveShadows:false});entity.enabled=false;this.cloneAssetMaterials(entity);this.app.root.addChild(entity);entries.push(entity);}return entries[index];}
  applyDrawOrder(entity,order){const records=this.assetMaterials.get(entity);if(records?.length){for(const record of records)record.meshInstance.drawOrder=order+(/edge/iu.test(record.name)?1:0);return;}for(const component of entity.findComponents?.("render")??[])for(const meshInstance of component.meshInstances??[])meshInstance.drawOrder=order;}
  cloneAssetMaterials(entity){const records=[];for(const component of entity.findComponents?.("render")??[]){for(const meshInstance of component.meshInstances??[]){const source=meshInstance.material,material=source.clone();meshInstance.material=material;records.push({meshInstance,sourceMaterial:source,material,materialOwned:true,name:String(source.name??""),diffuse:source.diffuse?.clone?.()??new pc.Color(1,1,1),emissive:source.emissive?.clone?.()??new pc.Color(0,0,0),opacity:Number(source.opacity??1),blendType:source.blendType,depthWrite:source.depthWrite!==false,useLighting:source.useLighting,cull:source.cull,diffuseMap:source.diffuseMap,emissiveMap:source.emissiveMap,opacityMap:source.opacityMap,diffuseMapChannel:source.diffuseMapChannel,emissiveMapChannel:source.emissiveMapChannel,opacityMapChannel:source.opacityMapChannel});}}this.assetMaterials.set(entity,records);}
  applyAssetAppearance(entity,assetId,colorToken,alpha,forceTint){const rgba=colorTokenToRgba(colorToken,[1,1,1,1]);for(const record of this.assetMaterials.get(entity)??[]){const material=record.meshInstance.material;if(material!==record.material){if(record.materialOwned)record.material.destroy();record.material=material;record.materialOwned=false;}const materialRole=gameplayAssetMaterialRole(assetId,record.name),marker=assetId==="athlete-marker/sphere-v1",tint=materialRole==="note_fill"||materialRole==="marker_fill"||forceTint&&assetId.startsWith("wall/");let diffuseR=record.diffuse.r,diffuseG=record.diffuse.g,diffuseB=record.diffuse.b,emissiveR=record.emissive.r,emissiveG=record.emissive.g,emissiveB=record.emissive.b;if(marker){if(materialRole==="marker_structure_charcoal"){diffuseR=.025;diffuseG=.032;diffuseB=.045;emissiveR=.025;emissiveG=.032;emissiveB=.045;}else if(materialRole==="marker_structure_white"){diffuseR=.88;diffuseG=.92;diffuseB=.98;emissiveR=.88;emissiveG=.92;emissiveB=.98;}else if(tint){diffuseR=rgba[0]*.68;diffuseG=rgba[1]*.68;diffuseB=rgba[2]*.68;emissiveR=diffuseR;emissiveG=diffuseG;emissiveB=diffuseB;}}else if(tint){diffuseR=rgba[0];diffuseG=rgba[1];diffuseB=rgba[2];emissiveR=rgba[0]*.32;emissiveG=rgba[1]*.32;emissiveB=rgba[2]*.32;}const state={kind:"asset",assetId,materialRole,sourceMaterial:record.sourceMaterial,diffuseR,diffuseG,diffuseB,emissiveR,emissiveG,emissiveB,opacity:record.opacity*alpha*rgba[3],blendType:alpha<1?pc.BLEND_NORMAL:record.blendType,depthWrite:alpha<1?false:record.depthWrite,depthTest:true,useLighting:marker?false:record.useLighting,cull:record.cull,diffuseMap:record.diffuseMap,emissiveMap:record.emissiveMap,opacityMap:record.opacityMap,diffuseMapChannel:record.diffuseMapChannel,emissiveMapChannel:record.emissiveMapChannel,opacityMapChannel:record.opacityMapChannel};if(materialStateIsUnchanged(material,this.materialStates.get(material),state))continue;material.diffuse.set(diffuseR,diffuseG,diffuseB);material.emissive.set(emissiveR,emissiveG,emissiveB);material.opacity=state.opacity;material.blendType=state.blendType;material.depthWrite=state.depthWrite;material.depthTest=state.depthTest;material.useLighting=state.useLighting;material.cull=state.cull;material.diffuseMap=state.diffuseMap;material.emissiveMap=state.emissiveMap;material.opacityMap=state.opacityMap;material.diffuseMapChannel=state.diffuseMapChannel;material.emissiveMapChannel=state.emissiveMapChannel;material.opacityMapChannel=state.opacityMapChannel;material.update();this.materialStates.set(material,state);}}
  acquireMarkerEntity(index){if(this.markerPoolMode!=="ready"){this.destroyMarkerPool();this.markerPoolMode="ready";}while(this.markerPool.length<=index){const resource=this.gameplayAssetLoader.resourceFor("athlete-marker/sphere-v1");if(!resource?.instantiateRenderEntity)return null;const entity=resource.instantiateRenderEntity({castShadows:false,receiveShadows:false});this.cloneAssetMaterials(entity);this.app.root.addChild(entity);this.markerPool.push(entity);}return this.markerPool[index];}
  acquireFallbackMarker(index){if(this.markerPoolMode!=="fallback"){this.destroyMarkerPool();this.markerPoolMode="fallback";}while(this.markerPool.length<=index)this.markerPool.push(this.makeEntity(`fallback-marker-${this.markerPool.length}`,"sphere"));return this.markerPool[index];}
  worldScaleForCssPx(sizeCssPx,position,sourceWorldSize=1){const cameraPosition=this.cameraEntity?.getPosition(),forward=this.cameraEntity?.forward,distance=cameraPosition&&forward?Math.max(.1,(position.x-cameraPosition.x)*forward.x+(position.y-cameraPosition.y)*forward.y+(position.z-cameraPosition.z)*forward.z):5,cssHeight=Math.max(1,this.heightCssPx||((this.canvas?.height??390)/Math.max(.1,this.devicePixelRatio))),pixelsPerUnit=cssHeight/(2*Math.tan((this.cameraEntity?.camera?.fov??48)*Math.PI/360)*distance);return clamp(sizeCssPx/(pixelsPerUnit*Math.max(.001,sourceWorldSize)),.25,6);}
  acquireFeedbackEntity(index,object){while(this.feedbackPool.length<=index)this.feedbackPool.push(this.createFeedbackGlyph());const entry=this.feedbackPool[index],feedback=object.feedback;if(!feedback)return null;entry.root.enabled=true;entry.root.name=object.id;const cameraForward=this.cameraEntity?.forward,position={x:object.position.x+feedback.offsetX,y:object.position.y+feedback.offsetY,z:object.position.z};entry.root.setPosition(position.x-(cameraForward?.x??0)*feedback.depthBias,position.y-(cameraForward?.y??0)*feedback.depthBias,position.z-(cameraForward?.z??-1)*feedback.depthBias);if(this.cameraEntity)entry.root.setRotation(this.cameraEntity.getRotation());const height=this.worldScaleForCssPx(feedback.apparentHeightCssPx,position)*feedback.scale;entry.quad.setLocalScale(height*3,1,height);const material=this.entityMaterials.get(entry.quad),texture=this.feedbackTextureFor(feedback.text);if(material){material.diffuse.set(1,1,1);material.emissive.set(1,1,1);material.diffuseMap=texture;material.emissiveMap=texture;material.opacityMap=texture;material.opacityMapChannel="a";material.opacity=feedback.alpha;material.blendType=pc.BLEND_NORMAL;material.depthTest=true;material.depthWrite=false;material.cull=pc.CULLFACE_NONE;material.update();}entry.text=feedback.text;entry.apparentHeightPx=feedback.apparentHeightCssPx*feedback.scale;return entry.root;}
  createFeedbackGlyph(){const root=new pc.Entity(`feedback-${this.feedbackPool.length}`,this.app),quad=this.makeDetachedEntity("feedback-quad","plane");quad.setLocalEulerAngles(90,0,0);root.addChild(quad);this.app.root.addChild(root);return{root,quad,text:"",apparentHeightPx:0};}
  acquireGuidanceHaloEntity(index,object){while(this.guidanceHaloPool.length<=index)this.guidanceHaloPool.push(this.createGuidanceHalo());const entry=this.guidanceHaloPool[index],width=object.scale.x,height=object.scale.y,thickness=.035+(4-(object.guidanceRank??3))*.012;entry.root.enabled=true;entry.root.name=object.id;entry.root.setPosition(object.position.x,object.position.y,object.position.z);if(this.cameraEntity)entry.root.setRotation(this.cameraEntity.getRotation());const [top,right,bottom,left]=entry.bars;top.setLocalPosition(0,height/2,0);bottom.setLocalPosition(0,-height/2,0);left.setLocalPosition(-width/2,0,0);right.setLocalPosition(width/2,0,0);top.setLocalScale(width,thickness,.025);bottom.setLocalScale(width,thickness,.025);left.setLocalScale(thickness,height,.025);right.setLocalScale(thickness,height,.025);for(const bar of entry.bars){this.useGameplayLayer(bar,"guidance_under");this.updateMaterial(bar,object.appearanceColor??"#d9f5ff",object.alpha,null,false,false);}return entry.root;}
  createGuidanceHalo(){const root=new pc.Entity(`guidance-halo-${this.guidanceHaloPool.length}`,this.app),bars=Array.from({length:4},(_,index)=>this.makeDetachedEntity(`guidance-halo-bar-${index}`,"box"));for(const bar of bars)root.addChild(bar);this.app.root.addChild(root);return{root,bars};}
  acquireGuidanceGlyphEntity(index,object){while(this.guidanceGlyphPool.length<=index)this.guidanceGlyphPool.push(this.createGuidanceGlyph());const entry=this.guidanceGlyphPool[index],text=object.guidanceText;if(typeof text!=="string")return null;entry.root.enabled=true;entry.root.name=object.id;entry.root.setPosition(object.position.x,object.position.y,object.position.z);if(this.cameraEntity)entry.root.setRotation(this.cameraEntity.getRotation());const height=this.worldScaleForCssPx(22,object.position);entry.quad.setLocalScale(height*2,1,height);this.useGameplayLayer(entry.quad,"guidance_over");const material=this.entityMaterials.get(entry.quad),texture=this.guidanceGlyphTextureFor(text);if(material){material.diffuse.set(1,1,1);material.emissive.set(1,1,1);material.diffuseMap=texture;material.emissiveMap=texture;material.opacityMap=texture;material.opacityMapChannel="a";material.opacity=1;material.blendType=pc.BLEND_NORMAL;material.depthTest=true;material.depthWrite=false;material.cull=pc.CULLFACE_NONE;material.update();}return entry.root;}
  createGuidanceGlyph(){const root=new pc.Entity(`guidance-glyph-${this.guidanceGlyphPool.length}`,this.app),quad=this.makeDetachedEntity("guidance-number-quad","plane");quad.setLocalEulerAngles(90,0,0);root.addChild(quad);this.app.root.addChild(root);return{root,quad};}
  guidanceGlyphTextureFor(text){let texture=this.guidanceGlyphTextures.get(text);if(texture){this.guidanceGlyphTextures.delete(text);this.guidanceGlyphTextures.set(text,texture);return texture;}while(this.guidanceGlyphTextures.size>=MAX_GUIDANCE_GLYPH_TEXTURES){const oldest=this.guidanceGlyphTextures.entries().next().value;if(!oldest)break;this.guidanceGlyphTextures.delete(oldest[0]);oldest[1].destroy();}const width=128,height=32,pixels=numberGlyphPixels(text,width,height),created=new pc.Texture(this.app.graphicsDevice,{name:`aero-guidance-number-${text}`,width,height,format:pc.PIXELFORMAT_RGBA8,mipmaps:false,minFilter:pc.FILTER_NEAREST,magFilter:pc.FILTER_NEAREST,addressU:pc.ADDRESS_CLAMP_TO_EDGE,addressV:pc.ADDRESS_CLAMP_TO_EDGE});created.lock().set(pixels);created.unlock();this.guidanceGlyphTextures.set(text,created);return created;}
  feedbackTextureFor(text){let texture=this.feedbackTextures.get(text);if(texture)return texture;const width=96,height=32,pixels=feedbackGlyphPixels(text,width,height),created=new pc.Texture(this.app.graphicsDevice,{name:`aero-feedback-${text.toLowerCase()}`,width,height,format:pc.PIXELFORMAT_RGBA8,mipmaps:false,minFilter:pc.FILTER_NEAREST,magFilter:pc.FILTER_NEAREST,addressU:pc.ADDRESS_CLAMP_TO_EDGE,addressV:pc.ADDRESS_CLAMP_TO_EDGE});created.lock().set(pixels);created.unlock();this.feedbackTextures.set(text,created);return created;}
  clearSceneObjects(){for(const entity of this.pool)entity.enabled=false;for(const entries of this.assetPools.values())for(const entity of entries)entity.enabled=false;for(const entry of this.feedbackPool)entry.root.enabled=false;for(const entry of this.guidanceGlyphPool)entry.root.enabled=false;for(const entry of this.guidanceHaloPool)entry.root.enabled=false;this.activeCount=0;this.sceneDiagnostics=emptySceneDiagnostics();}
  destroyPrimitiveEntity(entity){const material=this.entityMaterials.get(entity);if(material&&this.ownedMaterials.delete(material))material.destroy();entity.destroy();}
  destroyMarkerPool(){for(const entity of this.markerPool){const records=this.assetMaterials.get(entity)??[];for(const record of records)if(record.materialOwned)record.material.destroy();if(records.length)entity.destroy();else this.destroyPrimitiveEntity(entity);}this.markerPool=[];this.markerPoolMode="none";}
  destroyInstantiatedPools(){for(const entries of this.assetPools.values())for(const entity of entries){for(const record of this.assetMaterials.get(entity)??[])if(record.materialOwned)record.material.destroy();entity.destroy();}this.assetPools.clear();this.destroyMarkerPool();for(const entry of this.feedbackPool){this.destroyPrimitiveEntity(entry.quad);entry.root.destroy();}this.feedbackPool=[];for(const texture of this.feedbackTextures.values())texture.destroy();this.feedbackTextures.clear();for(const entry of this.guidanceGlyphPool){this.destroyPrimitiveEntity(entry.quad);entry.root.destroy();}this.guidanceGlyphPool=[];for(const texture of this.guidanceGlyphTextures.values())texture.destroy();this.guidanceGlyphTextures.clear();for(const entry of this.guidanceHaloPool){for(const bar of entry.bars)this.destroyPrimitiveEntity(bar);entry.root.destroy();}this.guidanceHaloPool=[];this.assetPoolGeneration=-1;this.materialStates=new WeakMap();}
  makeDetachedEntity(name,type){const entity=new pc.Entity(name,this.app);const material=this.makeMaterial();entity.addComponent("render",{type,material});this.entityMaterials.set(entity,material);return entity;}
  makeEntity(name,type){const entity=this.makeDetachedEntity(name,type);this.app.root.addChild(entity);return entity;}
  makeMaterial(){const material=new pc.StandardMaterial();material.useLighting=false;material.emissive=new pc.Color(1,1,1);material.diffuse=new pc.Color(1,1,1);material.opacity=1;material.blendType=pc.BLEND_NORMAL;material.depthTest=true;material.depthWrite=false;material.cull=pc.CULLFACE_NONE;material.update();this.ownedMaterials.add(material);return material;}
  updateMaterial(entity,colorToken,alpha,iconId,spent,depthWrite=false){const mappedMaterial=this.entityMaterials.get(entity);if(!mappedMaterial)return;const material=entity.findComponents?.("render")?.[0]?.meshInstances?.[0]?.material??mappedMaterial;if(material!==mappedMaterial){if(this.ownedMaterials.delete(mappedMaterial))mappedMaterial.destroy();this.entityMaterials.set(entity,material);}const rgba=colorTokenToRgba(colorToken,[0.85,0.95,1,1]),emissiveFactor=spent?.42:1,state={kind:"primitive",iconId,diffuseR:rgba[0],diffuseG:rgba[1],diffuseB:rgba[2],emissiveR:rgba[0]*emissiveFactor,emissiveG:rgba[1]*emissiveFactor,emissiveB:rgba[2]*emissiveFactor,opacity:alpha*rgba[3],blendType:pc.BLEND_NORMAL,depthTest:true,depthWrite,useLighting:false,cull:pc.CULLFACE_NONE,diffuseMap:null,emissiveMap:null,opacityMap:null,diffuseMapChannel:material.diffuseMapChannel,emissiveMapChannel:material.emissiveMapChannel,opacityMapChannel:material.opacityMapChannel};if(materialStateIsUnchanged(material,this.materialStates.get(material),state))return;material.diffuse.set(state.diffuseR,state.diffuseG,state.diffuseB);material.emissive.set(state.emissiveR,state.emissiveG,state.emissiveB);material.opacity=state.opacity;material.blendType=state.blendType;material.depthTest=state.depthTest;material.depthWrite=state.depthWrite;material.useLighting=state.useLighting;material.cull=state.cull;material.diffuseMap=state.diffuseMap;material.emissiveMap=state.emissiveMap;material.opacityMap=state.opacityMap;material.update();this.materialStates.set(material,state);}
  roleColor(role){return role==="left"?this.theme.leftHandColor:role==="right"?this.theme.rightHandColor:role==="guard"?this.theme.guardColor:role==="obstacle"?this.theme.obstacleColor:role==="safe"?"#56d6c9":this.theme.receptorColor;}
  addOverlayDisc(name,x,y,z,scale,color){const entity=this.makeEntity(name,"sphere");entity.setPosition(x,y,z);entity.setLocalScale(scale,scale,scale);this.updateMaterial(entity,color,1,null,false,false);this.overlayEntities.push(entity);}
  addOverlayLine(a,b,surface,color){const ap=gridPositionForNormalized(a.x/surface.viewportWidth,a.y/surface.viewportHeight,0.43),bp=gridPositionForNormalized(b.x/surface.viewportWidth,b.y/surface.viewportHeight,0.43),ax=ap.x,ay=ap.y,bx=bp.x,by=bp.y,dx=bx-ax,dy=by-ay,length=Math.hypot(dx,dy);const entity=this.makeEntity("landmark-line","box");entity.setPosition((ax+bx)/2,(ay+by)/2,0.43);entity.setLocalScale(0.025,length,0.02);entity.setEulerAngles(0,0,-Math.atan2(dx,dy)*180/Math.PI);this.updateMaterial(entity,color,0.9,null,false,false);this.overlayEntities.push(entity);}
  clearOverlayEntities(){for(const entity of this.overlayEntities)this.destroyPrimitiveEntity(entity);this.overlayEntities=[];for(const entity of this.markerPool)entity.enabled=false;this.cursorDiagnostics=Object.freeze({instanceCount:0,assetId:"athlete-marker/sphere-v1",roles:Object.freeze([]),depthTest:true,depthWrite:true});}
  manualTick(){if(!this.app)return;this.syncEnvironmentAnchor();if(this.atlasRestorePending&&this.iconAtlasData){this.createAtlasTexture();this.atlasRestorePending=false;}const now=globalThis.performance?.now?.()??Date.now();if(!this.appStarted){this.app.renderNextFrame=true;this.app.tick(now);this.app.start();this.appStarted=true;this.app.renderNextFrame=true;this.app.tick(now);}this.app.renderNextFrame=true;this.app.tick(now);}
  applyClearColor(){const rgba=colorTokenToRgba(this.background.colors[0],[0,0,0,0]);this.cameraEntity.camera.clearColor=new pc.Color(rgba[0],rgba[1],rgba[2],this.background.kind==="solid"?rgba[3]:0);}
  getCapabilities(){const degradations=[];if(!this.app)degradations.push("playcanvas_unavailable");const assets=this.gameplayAssetLoader.describe();if(assets.state==="fallback")degradations.push(`gameplay_assets_fallback:${assets.fallbackReason??"unknown"}`);if(assets.state==="error")degradations.push("gameplay_assets_error");return Object.freeze({serviceId:aeroPlayCanvasRendererServiceId,playcanvas:Boolean(this.app),engineVersion:"2.21.4",exactContainerResize:true,dprAware:true,contextLossRecovery:true,alphaMaskIcons:Boolean(this.iconTexture),canonicalGameplayAssets:assets.state==="ready",manualRendering:true,secondAnimationFrame:false,liveTuning:true,maxDevicePixelRatio:this.tuning.dprCap,degradations:Object.freeze(degradations)});}
  describe(){const activeIntentCount=new Set([...this.debugKeyboardIntents,...this.debugDomIntents]).size;return Object.freeze({serviceId:aeroPlayCanvasRendererServiceId,state:this.state,supported:Boolean(this.app),attached:Boolean(this.canvas&&this.app),contextLost:this.contextLost,destroyed:this.destroyed,frameCount:this.frameCount,drawCount:this.drawCount,contextRestoreCount:this.contextRestoreCount,viewportWidth:this.canvas?.width??0,viewportHeight:this.canvas?.height??0,widthCssPx:this.widthCssPx,heightCssPx:this.heightCssPx,devicePixelRatio:this.devicePixelRatio,themeId:this.themeId,themeVersion:this.themeVersion,themeHash:this.themeHash,tuningId:this.tuning.id,tuningVersion:this.tuning.version,tuningHash:this.tuning.hash,tuningRequiresRegeneration:false,visualProfile:this.visualProfile,visualProfileIdentity:this.visualProfile.identity,visualProfileSettings:this.visualProfile.settings,experimental:true,gameplayAssets:this.gameplayAssetLoader.describe(),environment:this.environmentOwner.describe(),sceneVisuals:this.sceneDiagnostics,cursors:this.cursorDiagnostics,iconAtlasReady:Boolean(this.iconTexture),iconAtlasError:this.iconAtlasError,errorMessage:this.errorMessage,debugCameraEnabled:this.debugEnabled,debugListenerCount:this.debugListeners.length,debugCaptureMode:this.debugCaptureMode,debugCameraSpeedMode:this.debugGuiSpeedMode,debugCameraBoostActive:this.debugShiftActive||this.debugGuiSpeedMode==="boost",debugActiveIntentCount:activeIntentCount,pointerLockActive:Boolean(this.canvas&&typeof document!=="undefined"&&document.pointerLockElement===this.canvas),pooledEntityCount:this.pool.length,activeEntityCount:this.activeCount,engine:"playcanvas",engineVersion:"2.21.4",manualRendering:true});}
  destroy(){if(this.destroyed)return this.describe();this.destroyed=true;this.detach();this.iconEntries.clear();this.iconAtlasData=null;this.state="destroyed";return this.describe();}
  fail(error){this.state="error";this.errorMessage=error instanceof Error?error.message:"Renderer operation failed";}
}
export function createAeroPlayCanvasRenderer(options){return new AeroPlayCanvasRenderer(options);}
function materialStateIsUnchanged(material,previous,state){if(!previous)return false;const keys=Object.keys(state);if(keys.length!==Object.keys(previous).length||keys.some((key)=>!Object.is(previous[key],state[key])))return false;return Object.is(material.diffuse.r,state.diffuseR)&&Object.is(material.diffuse.g,state.diffuseG)&&Object.is(material.diffuse.b,state.diffuseB)&&Object.is(material.emissive.r,state.emissiveR)&&Object.is(material.emissive.g,state.emissiveG)&&Object.is(material.emissive.b,state.emissiveB)&&Object.is(material.opacity,state.opacity)&&Object.is(material.blendType,state.blendType)&&Object.is(material.depthWrite,state.depthWrite)&&Object.is(material.depthTest,state.depthTest)&&Object.is(material.useLighting,state.useLighting)&&Object.is(material.cull,state.cull)&&Object.is(material.diffuseMap,state.diffuseMap)&&Object.is(material.emissiveMap,state.emissiveMap)&&Object.is(material.opacityMap,state.opacityMap)&&Object.is(material.diffuseMapChannel,state.diffuseMapChannel)&&Object.is(material.emissiveMapChannel,state.emissiveMapChannel)&&Object.is(material.opacityMapChannel,state.opacityMapChannel);}
function emptySceneDiagnostics(){return Object.freeze({sourceMode:"unavailable",assetRelease:null,assetGeneration:0,assetInstanceCounts:Object.freeze({}),fallbackInstanceCount:0,guardPairs:Object.freeze([]),whiteTintCount:0,tints:Object.freeze([]),removals:Object.freeze([]),feedback:Object.freeze([]),renderOrder:Object.freeze([])});}
function buildSceneDiagnostics(objects,mode,loader,renderedCounts,fallbackCount){const guards=new Map();for(const object of objects)if(object.guardPairKey){const pair=guards.get(object.guardPairKey)??[];pair.push(object);guards.set(object.guardPairKey,pair);}const guardPairs=[...guards.entries()].slice(0,8).map(([targetId,pair])=>{const [left,right]=pair.sort((a,b)=>a.position.x-b.position.x);const same=Boolean(left&&right&&left.assetId===right.assetId&&left.scale.x===right.scale.x&&left.scale.y===right.scale.y&&left.scale.z===right.scale.z&&left.rotationZRad===right.rotationZRad&&left.position.y===right.position.y&&left.position.z===right.position.z&&left.tintColor===right.tintColor&&left.position.x!==right.position.x);return Object.freeze({instanceCount:pair.length,assetId:left?.assetId??null,sameSourceAsset:same,sameMaterial:same,sameScale:same,sameOrientation:same,sameY:same,sameZ:same,xOnlyPlacementDifference:same});});const removals=[...new Map(objects.filter((entry)=>entry.removal&&entry.targetId).map((entry)=>[entry.targetId,entry])).values()].slice(0,8).map((entry)=>Object.freeze({elapsedMs:entry.removal.elapsedMs,durationMs:entry.removal.durationMs,progress:entry.removal.progress}));const feedback=objects.filter((entry)=>entry.feedback).slice(0,4).map((entry)=>Object.freeze({holdMs:entry.feedback.holdMs,fadeMs:entry.feedback.fadeMs,totalMs:entry.feedback.totalMs,elapsedMs:entry.feedback.elapsedMs,alpha:entry.feedback.alpha,depthBias:entry.feedback.depthBias,apparentHeightCssPx:entry.feedback.apparentHeightCssPx,offsetX:entry.feedback.offsetX,offsetY:entry.feedback.offsetY,scale:entry.feedback.scale,animation:entry.feedback.animation,depthTest:true,depthWrite:false}));return Object.freeze({sourceMode:mode,assetRelease:loader.release,assetGeneration:loader.generation,assetInstanceCounts:Object.freeze(Object.fromEntries([...renderedCounts.entries()].sort(([a],[b])=>a.localeCompare(b)))),fallbackInstanceCount:fallbackCount,guardPairs:Object.freeze(guardPairs),whiteTintCount:objects.filter((entry)=>entry.tintMix>=1&&entry.targetId).length,tints:Object.freeze(objects.filter((entry)=>entry.tintMix>0&&entry.targetId).slice(0,16).map((entry)=>Object.freeze({mix:entry.tintMix,color:entry.tintColor}))),removals:Object.freeze(removals),feedback:Object.freeze(feedback),renderOrder:Object.freeze([...new Set(objects.map((entry)=>entry.renderOrder))])});}
const GLYPHS=Object.freeze({G:["01110","10000","10111","10001","01110"],r:["00000","10110","11001","10000","10000"],e:["00000","01110","11111","10000","01110"],a:["00000","01110","00001","01111","01111"],t:["00100","11111","00100","00100","00011"],M:["10001","11011","10101","10001","10001"],i:["00100","00000","00100","00100","00100"],s:["00000","01111","10000","01110","11110"]});
function glyphPatterns(text){return [...text].map((letter)=>GLYPHS[letter]??["11111","10001","00110","00000","00100"]);}
function feedbackGlyphPixels(text,width,height){const pixels=new Uint8Array(width*height*4),patterns=glyphPatterns(text),scaleX=3,scaleY=4,total=patterns.length*6*scaleX-scaleX,startX=Math.floor((width-total)/2),startY=Math.floor((height-5*scaleY)/2),face=text==="Great"?[255,255,255,255]:[229,72,77,255],separation=text==="Great"?[23,26,34,255]:[255,255,255,255],cells=[];patterns.forEach((pattern,charIndex)=>pattern.forEach((row,rowIndex)=>[...row].forEach((on,columnIndex)=>{if(on==="1")cells.push({x:startX+(charIndex*6+columnIndex)*scaleX,y:startY+rowIndex*scaleY});})));const paint=(x,y,color)=>{if(x<0||x>=width||y<0||y>=height)return;const offset=(y*width+x)*4;pixels.set(color,offset);};for(const cell of cells)for(let y=-1;y<=scaleY;y+=1)for(let x=-1;x<=scaleX;x+=1)paint(cell.x+x,cell.y+y,separation);for(const cell of cells)for(let y=0;y<scaleY;y+=1)for(let x=0;x<scaleX;x+=1)paint(cell.x+x,cell.y+y,face);return pixels;}
const DIGIT_GLYPHS=Object.freeze({"0":["111","101","101","101","111"],"1":["010","110","010","010","111"],"2":["111","001","111","100","111"],"3":["111","001","111","001","111"],"4":["101","101","111","001","001"],"5":["111","100","111","001","111"],"6":["111","100","111","101","111"],"7":["111","001","010","010","010"],"8":["111","101","111","101","111"],"9":["111","101","111","001","111"]});
function numberGlyphPixels(text,width,height){const digits=[...text].slice(0,7),scale=4,total=Math.max(1,digits.length*4-1)*scale,startX=Math.floor((width-total)/2),startY=Math.floor((height-5*scale)/2),pixels=new Uint8Array(width*height*4);digits.forEach((digit,index)=>(DIGIT_GLYPHS[digit]??DIGIT_GLYPHS["0"]).forEach((row,y)=>[...row].forEach((on,x)=>{if(on!=="1")return;for(let py=0;py<scale;py+=1)for(let px=0;px<scale;px+=1){const offset=((startY+y*scale+py)*width+startX+(index*4+x)*scale+px)*4;pixels.set([255,255,255,255],offset);}})));return pixels;}
function normalizeCameraDeflection(value){if(value===null||value===undefined)return Object.freeze({active:false,xDeflection:0,yDeflection:0});if(!plainData(value)||Reflect.ownKeys(value).length!==3||!Object.hasOwn(value,"active")||!Object.hasOwn(value,"xDeflection")||!Object.hasOwn(value,"yDeflection")||typeof value.active!=="boolean"||![value.xDeflection,value.yDeflection].every((entry)=>typeof entry==="number"&&Number.isFinite(entry)&&entry>=-1&&entry<=1))throw new TypeError("Camera deflection must be an exact sanitized private record");return Object.freeze({active:value.active,xDeflection:Object.is(value.xDeflection,-0)?0:value.xDeflection,yDeflection:Object.is(value.yDeflection,-0)?0:value.yDeflection});}
function applyAxialDeadzone(value,deadzone){const magnitude=Math.abs(value);return magnitude<=deadzone?0:Math.sign(value)*(magnitude-deadzone)/(1-deadzone);}
function moveToward(from,to,maxDelta){return from+clamp(to-from,-maxDelta,maxDelta);}
function mixColorTokens(from,to,mix){const a=colorTokenToRgba(from,[1,1,1,1]),b=colorTokenToRgba(to,[1,1,1,1]),t=clamp(Number(mix),0,1);return`#${[0,1,2].map((index)=>Math.round((a[index]+(b[index]-a[index])*t)*255).toString(16).padStart(2,"0")).join("")}`;}
function gridPositionForNormalized(x,y,z){return{x:GRID_LEFT+clamp(x,0,1)*gameplayWorldGrid.columns*GRID_COLUMN_PITCH,y:GRID_TOP-clamp(y,0,1)*gameplayWorldGrid.rows*GRID_ROW_PITCH,z};}
function normalizeCursorGrid(value){if(!plainData(value)||![value.x,value.y,value.width,value.height].every(Number.isFinite)||value.width<=0||value.height<=0||value.x<0||value.y<0||value.x+value.width>1||value.y+value.height>1)throw new TypeError("Gameplay cursor grid is required");return value;}
function plainData(value){return value!==null&&typeof value==="object"&&!Array.isArray(value)&&Object.getPrototypeOf(value)===Object.prototype&&Object.values(Object.getOwnPropertyDescriptors(value)).every((entry)=>"value"in entry);}
function isOpaqueUppercaseColor(value){return typeof value==="string"&&/^#[0-9A-F]{6}$/u.test(value);}
function finiteNonNegative(value){return Number.isFinite(value)?Math.max(0,value):0;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function normalizeRadians(value){const full=Math.PI*2;return((value+Math.PI)%full+full)%full-Math.PI;}
function rgbaToHex(color){return`#${color.slice(0,3).map((entry)=>Math.round(clamp(entry,0,1)*255).toString(16).padStart(2,"0")).join("")}`;}
